service: LaravelServerlessApp

provider:
    name: aws
    region: us-east-1
    stage: ${opt:stage, 'dev'}
    runtime: provided
    environment:
      AWS_BUCKET: !Ref Storage
      AWS_PUBLIC_BUCKET: !Ref Assets
    iamRoleStatements:
      # Allow to put a file in the `my-bucket` S3 bucket
      - Effect: Allow
        Action: s3:*
        Resource:
          - Fn::Join: ['arn:aws:s3:::', [!Ref Storage, '/*']] # everything in the storage bucket

resources:
  Resources:
    # The S3 bucket that stores the assets
    Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: laravel-serverless-assets
    # The policy that makes the bucket publicly readable
    AssetsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref Assets # References the bucket we defined above
        PolicyDocument:
          Statement:
            -   Effect: Allow
                Principal: '*' # everyone
                Action: 's3:GetObject' # to read
                Resource: !Join ['/', [!GetAtt Assets.Arn, '*']] # things in the bucket
              # alternatively you can write out Resource: 'arn:aws:s3:::laravel-serverless-assets/*'
    Storage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: laravel-serverless-filesystem

package:
    # Directories to exclude from deployment
    exclude:
        - node_modules/**
        - public/storage
        - resources/assets/**
        - storage/**
        - tests/**

functions:
    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   http: 'ANY /'
            -   http: 'ANY /{proxy+}'
    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-74} # PHP
            - ${bref:layer.console} # The "console" layer

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
